# Generated by Django 2.2.2 on 2020-09-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_inventory_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'BUY'), (1, 'SELL')]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
