# Generated by Django 2.2.2 on 2020-09-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=15),
        ),
        migrations.AlterField(
            model_name='offer',
            name='transaction_type',
            field=models.CharField(choices=[('limit', 'LIMIT'), ('marker', 'MARKET')], max_length=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.PositiveSmallIntegerField(choices=[('buy', 'BUY'), ('sell', 'SELL')]),
        ),
    ]
