# Generated by Django 2.2.2 on 2020-09-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200908_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='transaction_type',
        ),
    ]
