# Generated by Django 2.2.2 on 2020-09-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_offer_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade_type',
        ),
    ]
