version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:alpine
    volumes:
    - ./redis-data:/app
  celery:
    build: .
    command: celery -A trading_platform worker -B -l INFO
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db